services:
  demo1:
    image: vicziani/demo2
    environment:
      SERVER_PORT: 8080
      SPRING_SECURITY_SAML2_RELYINGPARTY_REGISTRATION_KEYCLOAK_ENTITY_ID: courses
      SPRING_SECURITY_SAML2_RELYINGPARTY_REGISTRATION_KEYCLOAK_ASSERTINGPARTY_METADATA_URI: http://localhost:8080/realms/employees/protocol/saml/descriptor

    ports:
      - 8082:8080
